services:
  mongo:
    build:
      context: ./mongodb_rs
    container_name: db-csa
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_REPLICA_PORT: ${MONGO_REPLICA_PORT}
      MONGO_REPLICA_HOST: ${MONGO_REPLICA_HOST}
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
