import { Document, Types } from "mongoose";

interface AbastecimentoAgua {
  utilizaSeExclusivamenteAguaPotavelParaManipulacaoDeAlimentosAguaDeAbastecimentoPublicoOuSolucaoAlternativaComPotabilidadeAtestadaSemestralmentePorMeioDeLaudosLaboratoriais: number;
  instalacoesAbastecidasDeAguaCorrente: number;
  instalacoesDispoemDeConexoesComRedeDeEsgotoOuFossaSeptica: number;
  reservatorioEmAdequadoEstadoDeHigiene: number;
  reservatorioDevidamenteTampadoEConservadoLivreDeRachadurasVazamentosInfiltracoesDescascamentosDentreOutrosDefeitos: number;
  reservatorioDeAguaHigienizadoEmIntervaloMaximoDeSeisMesesSendoMantidosRegistrosDaOperacao: number;
  materialQueRevesteInternamenteOReservatorioDeAguaNaoComprometeAQualidadeDaAgua: number;
}

interface Estrutura {
  instalacoesSanitariasPossuemLavatoriosDeMaosEOsProdutosDestinadosAHigienePessoalPapelHigienicoSaboneteLiquidoInodoroAntissepticoOuSaboneteLiquidoInodoroEAntissepticoColetoresComTampaEAcionadosSemContatoManualEToalhasDePapelNaoRecicladoOuOutroSistemaHigienicoESegurosParaSecagemDasMaos: number;
  existeSeparacaoEntreAsDiferentesAtividadesPorMeiosFisicosOuPorOutrosMeiosEficazesDeFormaAEvitarAContaminacaoCruzada: number;
}

interface HigienizacaoInstalacoesEquipamentosMoveisUtensilios {
  instalacoesEquipamentosMoveisEUtensiliosMantidosEmCondicoesHigienicoSanitariaAdequadas: number;
  frequenciaAdequadaDeHigienizacaoDosEquipamentosMoveisEUtensilios: number;
  utensiliosUtilizadosNaHigienizacaoDeInstalacoesDistintosDaquelesUsadosParaHigienizacaoDasPartesDosEquipamentosEUtensiliosQueEntremEmContatoComOAlimento: number;
  diluicaoTempoDeContatoEModoDeUsoOuAplicacaoDosProdutosSaneantesObedeceAsInstrucoesRecomendadasPeloFabricante: number;
  produtosSaneantesRegularizadosPeloMinisterioDaSaude: number;
  areasDePreparacaoHigienizadasQuantasVezesForeMnecessariasEImediatamenteAposOTerminoDoTrabalho: number;
}

interface ControleIntegradoDeVetoresEPragasUrbanas {
  controleDeVetoresEPragasUrbanasExecutadosPorEmpresaEspecializadaDevidamenteRegularizada: number;
  existenciaDeUmConjuntoDeAcoesEficazesEContinuaComOObjetivoDeImpedirAAtracaoOAbrigoOAcessoEOuProliferacaoDeVetoresEPragasUrbanas: number;
  edificacoesInstalacoesEquipamentosMoveisEUtensiliosLivresDaPresencaDeAnimaisIncluindoVetoresEPragasUrbanas: number;
}

interface Manipuladores {
  osManipuladoresSaoAfastadosDaPreparacaoDeAlimentosQuandoApresentamLesoesEOuSintomasDeEnfermidades: number;
  lavamCuidadosamenteAsMaosAoChegarAoTrabalhoAntesEAposManipularOAlimentoAposQualquerInterrupcaoDoServicoAposTocarMateriaisContaminadosAposUsarOsSanitariosESempreQueSeFizerNecessario: number;
  naoFumamEFalamQuandoDesnecessarioCantamAssobiamEspirramCospemTossemComemManipulamDinheiroOuPraticamOutrosAtosQuePossamContaminarOAlimentoDuranteODesempenhoDasAtividades: number;
}

interface MateriaPrimaIngredientesEmbalagens {
  submetidosAInspecaoEAprovacaoNaRecepcao: number;
  materiasPrimasIngredientesEEmbalagensUtilizadosParaPreparacaoEmCondicoesHigienicoSanitariasAdequadas: number;
  embalagensPrimariasDasMateriasPrimasEDosIngredientesIntegras: number;
  utilizacaoDasMateriasPrimasEIngredientesRespeitaOPrazoDeValidadeOuSeObservaAOrdemDeEntrada: number;
  materiasPrimasFracionadasAdequadamenteAcondicionadasEIdentificadasComNoMinimoAsSeguintesInformacoesDesignacaoDoProdutoDataDeFracionamentoEPrazoDeValidadeAposAberturaOuRetiradaDaEmbalagemOriginal: number;
  temperaturaDasMateriasPrimasEIngredientesPereciveisVerificadaNaRecepcaoENoArmazenamento: number;
  geloUtilizadoEmAlimentosFabricadoAPartirDeAguaPotavelEMantidoEmCondicaoHigienicoSanitaria: number;
}

interface PreparoDoAlimento {
  lavatoriosDaAreaDePreparacaoDotadosDosProdutosDestinadosAHigieneDasMaosSaboneteLiquidoInodoroAntissepticoOuSaboneteLiquidoInodoroEProdutoAntissepticoToalhasDePapelNaoRecicladoOuOutroSistemaHigienicoESeguroDeSecagemDasMaos: number;
  duranteOPreparoAquelesQueManipulamAlimentosCrusRealizamALavagemEAAntissepsiaDasMaosAntesDeManusearAlimentosPreparados: number;
  produtosPereciveisExpostosATemperaturaAmbienteSomentePeloTempoMinimoNecessarioParaPreparacaoDoAlimento: number;
  descongelamentoConduzidoConformeOrientacaoDoFabricanteEUtilizandoUmaDasSeguintesTecnicasRefrigeracaoATemperaturaInferiorA5COuEmFornoDeMicroOndasQuandoOAlimentoForSubmetidoImediatamenteACocao: number;
  alimentosSubmetidosAoDescongelamentoMantidosSobRefrigeracaoSeNaoForeImediatamenteUtilizadosENaoSeRecongela: number;
  tratamentoTermicoGaranteQueTodasAsPartesDoAlimentoAtinjamATemperaturaDeNoMinimo70COuOutraCombinacaoDeTempoETemperaturaDesdeQueAssegureAQualidadeHigienicoSanitariaDosAlimentos: number;
  avaliaSeAEficaciaDoTratamentoTermico: number;
  possuemTermometroComprovadamenteCalibradoParaAAfericaoDaTemperaturaDosAlimentos: number;
  aposOResfriamentoAlimentoPreparadoConservadoSobRefrigeracaoATemperaturasInferioresA5COuCongeladoATemperaturaIgualOuInferiorA18: number;
  alimentosConsumidosCrusQuandoAplicavelSubmetidosAProcessoDeHigienizacaoComProdutosRegularizadosEAplicadosDeFormaAEvitarAPresencaDeResiduos: number;
  evitaSeOContatoDiretoOuIndiretoEntreAlimentosCrusSemiProntosEProntosParaOConsumo: number;
  temperaturaDoAlimentoPreparadoNoResfriamentoReduzidaDe60CA10CEmAte2Horas: number;
}

interface ArmazenamentoTransporteExposicaoDoAlimentoPreparado {
  alimentoPreparadoArmazenadoIdentificado: number;
  prazoMaximoConsumo5Dias4COuInferior: number;
  prazoMaximoConsumoAcima4CAbaixo5C: number;
  manipuladoresMinimizamRiscoContaminacao: number;
  alimentoPreparadoConservado5COuInferior: number;
  alimentosPreparadosAcima60C: number;
  temperaturaEquipamentosExposicaoMonitorada: number;
  alimentosArmazenadosIdentificadosProtegidos: number;
  armazenamentoTransporteTemperaturaAdequada: number;
}

interface ResponsabilidadeDocumentacaoRegistro {
  possuiUmResponsavelPelasAtividadesDeManipulacaoDeAlimentosResponsavelTecnicoProprietarioOuFuncionarioDesignadoDevidamenteCapacitado: number;
  empresaSegueOManualDeBoasPraticasEOsProcedimentosOperacionaisPadronizados: number;
}

interface AreasExternas {
  livresDeObjetosEmDesusoOuEstranhosAoAmbiente: number;
}

interface AreasInternas {
  livresDeObjetosEmDesusoOuEstranhosAoAmbiente: number;
}

interface EdificacaoEInstalacoes {
  projetadasDeFormaAPossibilitarUmFluxoOrdenadoESemCruzamentosEmTodasAsEtapasDePreparacaoDeAlimentos: number;
  projetadasParaFacilitarAsOperacoesDeManutencaoLimpezaEQuandoForOCasoDesinfeccao: number;
  acessoAsInstalacoesIndependenteENaoComumAOutrosUsos: number;
  existeControleDoAcessoDePessoal: number;
  dimensionamentoCompativelComTodasAsOperacoes: number;
  existeSeparacaoEntreAsDiferentesAtividadesPorMeiosFisicosOuPorOutrosMeiosEficazesDeFormaAEvitarAContaminacaoCruzada: number;
}

interface InstalacoesFisicasPisos {
  possuemRevestimentosLisosImpermeaveisELavaveis: number;
  emAdequadoEstadoDeConservacaoLivresDeRachadurasTrincasBuracosEOutrosDefeitos: number;
}

interface InstalacoesFisicasParedes {
  possuemRevestimentosLisosImpermeaveisELavaveis: number;
  emAdequadoEstadoDeConservacaoLivresDeRachadurasTrincasInfiltracoesBoloresDescascamentosDentreOutrosDefeitos: number;
}

interface InstalacoesFisicasTetos {
  possuemRevestimentosLisosImpermeaveisELavaveis: number;
  tetoDaAreaDeManipulacaoEArmazenamentoDeAlimentosMantidoEmAdequadoEstadoDeConservacaoLivreDeGoteirasVazamentosInfiltracoesBoloresDescascamentosDentreOutrosDefeitos: number;
  tetoDasDemaisAreasMantidoEmAdequadoEstadoDeConservacaoLivreDeGoteirasVazamentosInfiltracoesBoloresDescascamentosDentreOutrosDefeitos: number;
}

interface Portas {
  portasMantidasAjustadasAosBatentesBemFechadasEVedadas: number;
  portasDaAreaDePreparacaoEArmazenamentoPossuemFechamentoAutomatico: number;
  portasExternasNaAreaDePreparacaoEArmazenamentoProvidasDeTelasMilimetradasLimpasEmBomEstadoDeConservacaoEAjustadasAosBatentes: number;
  telasRemoviveisParaFacilitarALimpezaPeriodica: number;
}

interface JanelasEOOutrasAberturasSistemaDeExaustao {
  janelasMantidasAjustadasAosBatentesBemFechadasEVedadas: number;
  areaDePreparacaoEArmazenamentoProvidasDeTelasMilimetradasLimpasEmBomEstadoDeConservacaoEAjustadasAosBatentes: number;
  telasRemoviveisParaFacilitarALimpezaPeriodica: number;
}

interface RalosEGrelhas {
  ralosSifonadosQuandoPresentes: number;
  quandoPresentesAsGrelhasPossuemDispositivoDeFechamento: string;
}

interface CaixaDeGorduraEEsgoto {
  possuemDimensaoCompativelAoVolumeDeResiduos: number;
  localizadasForaDaAreaDePreparacaoEArmazenamentoDeAlimentos: number;
  apresentamAdequadoEstadoDeConservacaoEFuncionamento: number;
}

interface Iluminacao {
  iluminacaoDaAreaDePreparacaoProporcionaAVisualizacaoAdequada: number;
  luminariasLocalizadasSobreAAreaDePreparacaoDosAlimentosApropriadasEProtegidasContraExplosaoEQuedasAcidentais: number;
}

interface InstalacoesEletricas {
  embutidasOuProtegidasEmTubulacoesExternas: number;
  integraisPossibilitandoAHigienizacaoDosAmbientes: number;
}

interface Ventilacao {
  garanteARenovacaoDoArEManutencaoDoAmbienteEmCondicoesQueNaoComprometamAQualidadeHigienicoSanitariaDoAlimentoLivreDeFungosFumacaPosCondensacaoDeVapores: number;
  adequadoFluxoDeArNaoIncideDiretamenteSobreOsAlimentos: number;
  fluxoDeArNaoCirculaDeAreasContaminadasParaAreasLimpas: number;
  equipamentosEFiltrosParaClimatizacaoBemConservados: number;
  realizaSeLimpezaDosComponentesDoSistemaDeClimatizacaoATrocaDeFiltrosEManutencaoProgramadaEPeriodicaDestesEquipamentos: number;
  existeRegistroDaLimpezaDosComponentesDosSistemasDeClimatizacaoDaTrocaDeFiltrosEDaManutencaoProgramadaEPeriodicaDestesEquipamentos: number;
}

interface InstalacoesSanitariasEVestarios {
  localizadosSemComunicacaoDiretaComAAreaDePreparacaoEArmazenamento: number;
  mantidosOrganizadosLimposEEmAdequadoEstadoDeConservacao: number;
  portasExternasComFechamentoAutomatico: number;
  instalacoesSanitariasPossuemLavatoriosDeMaosEOsProdutosDestinadosAHigienePessoal: number;
}

interface LavatorioAreaDeManipulacao {
  existeLavatorioExclusivoParaAHigieneDasMaosNaAreaDeManipulacaoEmPosicoesEstrategicasEmRelacaoAoFluxoDePreparo: number;
  emNumeroSuficienteDeModoAAtenderTodaAAreaDePreparacao: number;
  possuemSaboneteLiquidoInodoroAntissepticoOuSaboneteLiquidoInodoroEProdutoAntissepticoToalhasDePapelNaoRecicladoOuOutroSistemaHigienicoESeguroDeSecagemDasMaos: number;
  possuemColetoresDePapelAcionadosSemContatoManual: number;
}

interface Equipamentos {
  equipamentosQueEntramEmContatoComAlimentosDeMateriaisQueNaoTransmitamSubstanciasToxicasOdoresNemSaboresAosAlimentos: number;
  mantidosEmAdequadoEstadoDeConservacaoResistentesACorrosaoEARepetidasOperacoesDeLimpezaEDesinfeccao: number;
  equipamentosUtilizadosNaPreparacaoEmbalagemArmazenamentoTransporteDistribuicaoEExposicaoAVendaDosAlimentosPossuemAsSuperficiesLisasImpermeaveisLavaveisEIsentasDeRugosidadesFrestasEOOutrasImperfeicoes: number;
  realizamSeManutencoesProgramadasEPeriodicasBemComoORegistroDessaOperacao: number;
  possuemTermometroComprovadamenteCalibradoParaAAfericaoDaTemperaturaDosAlimentos: number;
}

interface Utensilios {
  utensiliosQueEntramEmContatoComAlimentosDeMateriaisQueNaoTransmitamSubstanciasToxicasOdoresNemSaboresAosAlimentos: number;
  mantidosEmAdequadoEstadoDeConservacaoResistentesACorrosaoEARepetidasOperacoesDeLimpezaEDesinfeccao: number;
  utensiliosUtilizadosNaPreparacaoEmbalagemArmazenamentoTransporteDistribuicaoEExposicaoAVendaDosAlimentosPossuemAsSuperficiesLisasImpermeaveisLavaveisEIsentasDeRugosidadesFrestasEOOutrasImperfeicoes: number;
}

interface Moveis {
  moveisQueEntramEmContatoComAlimentosDeMateriaisQueNaoTransmitamSubstanciasToxicasOdoresNemSaboresAosAlimentos: number;
  mantidosEmAdequadoEstadoDeConservacaoResistentesACorrosaoEARepetidasOperacoesDeLimpezaEDesinfeccao: number;
  moveisUtilizadosNaPreparacaoEmbalagemArmazenamentoTransporteDistribuicaoEExposicaoAVendaDosAlimentosPossuemAsSuperficiesLisasImpermeaveisLavaveisEIsentasDeRugosidadesFrestasEOOutrasImperfeicoes: number;
}

export interface IListaVerificacao extends Document {
  abastecimentoAgua: AbastecimentoAgua;
  estrutura: Estrutura;
  higienizacaoInstalacoesEquipamentosMoveisUtensilios: HigienizacaoInstalacoesEquipamentosMoveisUtensilios;
  controleIntegradoDeVetoresEPragasUrbanas: ControleIntegradoDeVetoresEPragasUrbanas;
  manipuladores: Manipuladores;
  materiaPrimaIngredientesEmbalagens: MateriaPrimaIngredientesEmbalagens;
  preparoDoAlimento: PreparoDoAlimento;
  armazenamentoTransporteExposicaoDoAlimentoPreparado: ArmazenamentoTransporteExposicaoDoAlimentoPreparado;
  responsabilidadeDocumentacaoRegistro: ResponsabilidadeDocumentacaoRegistro;
  areasExternas: AreasExternas;
  areasInternas: AreasInternas;
  edificacaoEInstalacoes: EdificacaoEInstalacoes;
  instalacoesFisicasPisos: InstalacoesFisicasPisos;
  instalacoesFisicasParedes: InstalacoesFisicasParedes;
  instalacoesFisicasTetos: InstalacoesFisicasTetos;
  portas: Portas;
  janelasEOOutrasAberturasSistemaDeExaustao: JanelasEOOutrasAberturasSistemaDeExaustao;
  ralosEGrelhas: RalosEGrelhas;
  caixaDeGorduraEEsgoto: CaixaDeGorduraEEsgoto;
  iluminacao: Iluminacao;
  instalacoesEletricas: InstalacoesEletricas;
  ventilacao: Ventilacao;
  instalacoesSanitariasEVestarios: InstalacoesSanitariasEVestarios;
  lavatorioAreaDeManipulacao: LavatorioAreaDeManipulacao;
  equipamentos: Equipamentos;
  utensilios: Utensilios;
  moveis: Moveis;

  idAvaliacao: Types.ObjectId;
}
